package ru.burmistrov.soaptm.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-16T17:25:18.116+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.soaptm.burmistrov.ru/", name = "IAuthEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface IAuthEndpoint {

    @WebMethod
    @RequestWrapper(localName = "auth", targetNamespace = "http://endpoint.api.soaptm.burmistrov.ru/", className = "ru.burmistrov.soaptm.api.endpoint.Auth")
    @ResponseWrapper(localName = "authResponse", targetNamespace = "http://endpoint.api.soaptm.burmistrov.ru/", className = "ru.burmistrov.soaptm.api.endpoint.AuthResponse")
    public void auth(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    ) throws Exception_Exception;
}
