package ru.burmistrov.soaptm.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-05-16T15:51:54.136+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.soapTM.burmistrov.ru/", name = "ITaskEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ITaskEndpoint {

    @WebMethod
    @RequestWrapper(localName = "removeTaskById", targetNamespace = "http://endpoint.api.soapTM.burmistrov.ru/", className = "ru.burmistrov.soaptm.api.endpoint.RemoveTaskById")
    @ResponseWrapper(localName = "removeTaskByIdResponse", targetNamespace = "http://endpoint.api.soapTM.burmistrov.ru/", className = "ru.burmistrov.soaptm.api.endpoint.RemoveTaskByIdResponse")
    public void removeTaskById(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "taskId", targetNamespace = "")
        java.lang.String taskId
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "createTask", targetNamespace = "http://endpoint.api.soapTM.burmistrov.ru/", className = "ru.burmistrov.soaptm.api.endpoint.CreateTask")
    @ResponseWrapper(localName = "createTaskResponse", targetNamespace = "http://endpoint.api.soapTM.burmistrov.ru/", className = "ru.burmistrov.soaptm.api.endpoint.CreateTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.soaptm.api.endpoint.TaskDto createTask(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "projectId", targetNamespace = "")
        java.lang.String projectId,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "dateEnd", targetNamespace = "")
        java.lang.String dateEnd
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "findOneTaskById", targetNamespace = "http://endpoint.api.soapTM.burmistrov.ru/", className = "ru.burmistrov.soaptm.api.endpoint.FindOneTaskById")
    @ResponseWrapper(localName = "findOneTaskByIdResponse", targetNamespace = "http://endpoint.api.soapTM.burmistrov.ru/", className = "ru.burmistrov.soaptm.api.endpoint.FindOneTaskByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.soaptm.api.endpoint.TaskDto findOneTaskById(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "projectId", targetNamespace = "")
        java.lang.String projectId
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateTaskById", targetNamespace = "http://endpoint.api.soapTM.burmistrov.ru/", className = "ru.burmistrov.soaptm.api.endpoint.UpdateTaskById")
    @ResponseWrapper(localName = "updateTaskByIdResponse", targetNamespace = "http://endpoint.api.soapTM.burmistrov.ru/", className = "ru.burmistrov.soaptm.api.endpoint.UpdateTaskByIdResponse")
    public void updateTaskById(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId,
        @WebParam(name = "projectId", targetNamespace = "")
        java.lang.String projectId,
        @WebParam(name = "taskId", targetNamespace = "")
        java.lang.String taskId,
        @WebParam(name = "newName", targetNamespace = "")
        java.lang.String newName,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "dateEnd", targetNamespace = "")
        java.lang.String dateEnd
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "findAllTasksInProject", targetNamespace = "http://endpoint.api.soapTM.burmistrov.ru/", className = "ru.burmistrov.soaptm.api.endpoint.FindAllTasksInProject")
    @ResponseWrapper(localName = "findAllTasksInProjectResponse", targetNamespace = "http://endpoint.api.soapTM.burmistrov.ru/", className = "ru.burmistrov.soaptm.api.endpoint.FindAllTasksInProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.burmistrov.soaptm.api.endpoint.TaskDto> findAllTasksInProject(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception_Exception;
}
